---
- name: Deploying LAMP Stack on Centos 8
  hosts: all
  gather_facts: true
  remote_user: ansible
  become: yes
  vars:
        mysql_root_password: "pass4mysql!"

  tasks:
    - name: Installing Apache Server
      yum: name=httpd state=latest

    - name: Install MariaDB
      yum:
        name:
          - mariadb-server
          - mariadb-devel
          - mariadb-connectot-odbc
          - mariadb-server-utils
          - python3-PyMySQL
        state: latest
        
    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started
    - name: mysql_root_password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        check_implicit_admin: true
        password: "{{ mysql_root_password }}"
        host: localhost
