---
- name: Deploying LAMP Stack on Centos 8
  hosts: ansible2
  remote_user: ansible
  become: yes


  tasks:
    - name: Installing Apache Server
      yum: name=httpd state=latest

    - name: Start Apache service
      yum: name=httpd state=started

    - name: Installing MariaDB Server
      yum:
       name:
       - mariadb-server
       - mariadb-devel
       - mariadb-connectot-odbc
       - mariadb-server-utils
       - python3-PyMySql
       - php
       state: latest

    - name: Start MariadDB Server Service
      service: name=mariadb state=started

    - name: Update MariaDB Server root password
      mysql_user:
        name: root
        host: ansible2
        password: pass4mysql!
        login_user: root
        check_implicit_admin: yes
        priv: "*-*:ALL,GRANT"

    - name: Create a new database called test
      mysql_db: name=test state=present login_user:root login_password=pass4mysql!
